### ISSUE TITLE
Questions: how to get the aggregate result for every hour

### ISSUE THREAD

**Issue by gf53520** [Stratio/Sparta#1545]
Hi Stratio team,
    I am researching  Stratio project code. 
    Interesting about the blog that http://blog.stratio.com/how-to-aggregate-data-in-real-time-with-stratio-sparta/.  I am to be curious about the aggregate result for every hour. Because the  input data  the spark streaming  is batch data(Stratio default spark streaming window is 2s ),  and the question is  how to get the aggregate result for every hour. I guess Stratio  realize this by interacting with other outer storage system, but I can't find the code in Stratio. Can you give me a help? thx.

**Comment by danielcsant** [comment]
Hi,

You are right, Stratio Sparta makes use of HDFS in production environments or the file system for testing pourposes. Actually this is a feature of Spark Streaming called checkpointing. For example when aggregating by hour and for operations like Sum, Sparta keeps the last state for that sum in this checkpoint.

Thanks for your interest!
