### ISSUE TITLE
Error: getaddrinfo ENOTFOUND sodio.stratio.com

### ISSUE THREAD

**Issue by ClassNotFoundExp** [Stratio/Sparta#1585]
why I cannot get sodio.stratio.com???

**Comment by danielcsant** [comment]
Hi,
Does occur the same in branch **branch-0.9**?

**Comment by ClassNotFoundExp** [comment]
I hit it use branch master，using mvn clean package -Ppackage,I solved it by changing  registry http://registry.npm.taobao.org/ in web model，and the branch master I builded,it need java8??
Future[(Boolean, Process)] {
      val sparkProcess = sparkLauncher.launch()
      (sparkProcess.waitFor(20, TimeUnit.SECONDS), sparkProcess)
    } onComplete {
      case Success((exitCode, sparkProcess)) =>
        sparkLauncherStreams(exitCode, sparkProcess)
      case Success((exitCode, sparkProcess)) =>
        sparkLauncherStreams(exitCode, sparkProcess)
      case Failure(exception) =>
        log.error(exception.getMessage)
        throw exception
    }
in this code, sparkProcess.waitFor(20, TimeUnit.SECONDS),java7 has no this code. @danielcsant

**Comment by danielcsant** [comment]
Hi again,

That is solved in [Release 0.9.5](https://github.com/Stratio/Sparta/releases/tag/0.9.5) which has the more recent version of Stratio Sparta. We will rebase it to master ASAP. Meanwhile you can use this release.

Regards
