### ISSUE TITLE
Policy status reset to NotStarted, when http server start

### ISSUE THREAD

**Issue by AndyRao** [Stratio/Sparta#1602]
I notice that status of all policies will be set to NotStarted when sparta http server start. I think this can cause inconsistency. Because if a spark streaming application is running, his status should not be set to NotStarted, even if sparta http server died for some reason and start again.

**Comment by danielcsant** [comment]
Hi, 

That behaviour occurs when Sparta is configured to run in local mode. This is, when Sparta service is stopped then Spark Streaming applications are stopped as well.

Running Sparta with a resource manager like Mesos or YARN the behaviour will be what you expect. Status are kept

Regards,

**Comment by AndyRao** [comment]
Ok I will check that with a yarn, thanks
