### ISSUE TITLE
Kafka Avro Deserialization and REST End-point for Output

### ISSUE THREAD

**Issue by skilledmonster** [Stratio/sparta#1619]
Hi -
[Not sure if this is the right forum and because I haven't seen user groups available, I am posting it here. Feel free to redirect me to appropriate channel]

My messages in Kafka are custom Avro Serialized. When I configure the Input Type in Sparta to Kafka, it may have trouble for deserializing the Avro messages. I am wondering if there is a way to extend Kafka Input Type to support custom Avro deserialization?

Also, for Output Type, is there a REST Output Type? Essentially, after pre-aggregations, I would want to post the output to a REST end-point with JSON as body content.

Thoughts?

**Comment by skilledmonster** [comment]
Does anyone know if this project/company still active?

**Comment by skilledmonster** [comment]
Guys any help here ?

**Comment by danielcsant** [comment]
Hi,

You need to make your custom implementation of the Kafka input and the REST output. 
To make the Kafka input you can base on the one  is already done. You should add the possibility to  add an Avro schema to the input configuration.

Regards

**Comment by compae** [comment]
Hi,

If you need one Output rest, you can implement this new output extending the Output SDK, similar to kafkaOutput or RedisOutput.

If you want to make one PR I can check all and merge in master.

Thanks for all.

**Comment by skilledmonster** [comment]
Ok...sounds good! Any help in setting up a quick workspace? A simple doc or instructions would help.

Thanks!

**Comment by skilledmonster** [comment]
@danielcsant @compae - guys any help in setting up workspace?

**Comment by compae** [comment]
You need install Intellij and scala plugin. Then you can import the project as "maven project".

You can make one fork of the repository in your Github account, develop the feature in one branch and then make one Pull Request in the master branch of stratio/sparta repository.

Thanks.

**Comment by compae** [comment]
If you need one transformation with Avro Serialization you can see the ingestion parser.
