### ISSUE TITLE
PrintOutput output does not print correct count of items

### ISSUE THREAD

**Issue by raulsaeztapia** [Stratio/Sparta#165]
When you are counting a dimension with:

```
  "outputs": [
    {
      "name": "print",
      "elementType": "PrintOutput",
      "configuration": {
        "isAutoCalculateId":"true",
        "dateBucket": "minute",
        "granularity": "minute"
      }
    }
  ],
"operators": [
    {   
      "name": "count-operator",
      "elementType": "CountOperator",
      "configuration": {}
    }
]
```

I am getting prints like this:

```
Count: 1
```

however, in my test, were caught 5.000 items. It seems as counter printed is the number of streams, that ever will be only one, but is not the number of items.

**Comment by raulsaeztapia** [comment]
The CSV file that Sparkta was ingesting was like this:
```
.....
Pepe,12341234121234567890,312
Pepe,12341234121234567890,246
Pepe,12341234121234567890,992
Pepe,12341234121234567890,129
Pepe,12341234121234567890,87
Pepe,12341234121234567890,873
.....
```

**Comment by raulsaeztapia** [comment]
This is the policy file that I was deploying:
```
{
  "name": "SMF-policy",
  "duration": 10000,
  "saveRawData": "false",
  "inputs": [
    {
        "name": "in",
        "elementType": "KafkaInput",
        "configuration": {
            "topics": "test",
            "kafkaParams.zookeeper.connect" : "172.17.42.1:2181",
            "kafkaParams.group.id" : "kafka-test",
            "storageLevel" : "MEMORY_AND_DISK_SER_2"
        }
    }
  ],
  "dimensions": [
    {
      "dimensionType": "PassthroughBucketer",
      "name": "name"
    },
    {
      "dimensionType": "PassthroughBucketer",
      "name": "ccc"
    },
    {
      "dimensionType": "PassthroughBucketer",
      "name": "money"
    }
  ],
  "rollups": [
    {
      "dimensionAndBucketTypes": [
        {
          "dimensionName": "name",
          "bucketType": "identity"
        }
      ]
    },
    {
      "dimensionAndBucketTypes": [
        {
          "dimensionName": "ccc",
          "bucketType": "identity"
        }
      ]
    }
  ],
  "outputs": [
    {
      "name": "print",
      "elementType": "PrintOutput",
      "configuration": {
        "isAutoCalculateId":"true",
        "dateBucket": "minute",
        "granularity": "minute"
      }
    }
  ],
  "operators": [
    {
      "name": "count-operator",
      "elementType": "CountOperator",
      "configuration": {}
    }
  ],
  "parsers": [
    {
      "name": "morphline-parser",
      "elementType": "MorphlinesParser",
      "configuration": {
        "morphline": {
          "id": "morphline1",
          "importCommands": [
            "org.kitesdk.**",
            "com.stratio.ingestion.morphline.**"
          ],
          "commands" : [
            { 
              "readCSV" : {
                "separator" : ",",
                "columns" : ["name","ccc","money"],
                "ignoreFirstLine" : "true",
                "trim" : "true",
                "charset" : "UTF-8",
                "quoteChar" : "\"",
                "commentPrefix" : "#"
              }
            } 
          ]
        }
      }
    }
  ]
}
```

**Comment by gserranojc** [comment]
I think that this problem is caused for one bug in output sdk. In the PR of cassandra full text is solved.

**Comment by Brezyll** [comment]
Hi Raul, after some changes this issue seems solved.

This is the Input we tried: 
Pepe,12341234121234567890,312
Juan,12341235841234567890,246
Pepe,12341234121234567890,992
Ramon,12384212254546844121,129
Pepe,12341234121234567890,87
Pepe,12341234121234567890,873

The Output:
[12384212254546844121,Ramon,2015-05-27 9:53:00.0,  1384212254546844121_Ramon_2015-05-27 09:53:00.0]

[12341235841234567890,Juan,2015-05-27 09:53:00.0,12341235841234567890_Juan_2015-05-27 09:53:00.0]

[12341234121234567890,Pepe,2015-05-27 09:53:00.0, 12341234121234567890_Pepe_2015-05-27 09:53:00.0]

And the policy(We aggregate by Name and CCC):

{
  "name": "SMF-policy",
  "duration": 10000,
  "saveRawData": "false",
  "inputs": [
    {
      "name": "in",
      "elementType": "KafkaInput",
      "configuration": {
        "topics": "finalcount",
        "kafkaParams.zookeeper.connect" : "localhost:2181",
        "kafkaParams.group.id" : "kafka-test",
        "storageLevel" : "MEMORY_AND_DISK_SER_2"
      }
    }
  ],
  "dimensions": [
    {
      "dimensionType": "PassthroughBucketer",
      "name": "name"
    },
    {
      "dimensionType": "PassthroughBucketer",
      "name": "ccc"
    },
    {
      "dimensionType": "PassthroughBucketer",
      "name": "money"
    }
  ],
  "rollups": [
    {
      "dimensionAndBucketTypes": [
        {
          "dimensionName": "name",
          "bucketType": "identity"
        },
        {
          "dimensionName": "ccc",
          "bucketType": "identity"
        }
      ],
      "operators": ["count-operator"]
    }
  ],
  "outputs": [
    {
      "name": "print",
      "elementType": "PrintOutput",
      "configuration": {
        "isAutoCalculateId":"true",
        "dateBucket": "minute",
        "granularity": "minute"
      }
    }
  ],
  "operators": [
    {
      "name": "count-operator",
      "elementType": "CountOperator",
      "configuration": {}
    }
  ],
  "parsers": [
    {
      "name": "morphline-parser",
      "elementType": "MorphlinesParser",
      "configuration": {
        "morphline": {
          "id": "morphline1",
          "importCommands": [
            "org.kitesdk.**",
            "com.stratio.ingestion.morphline.**"
          ],
          "commands" : [
            {
              "readCSV" : {
                "separator" : ",",
                "columns" : ["name","ccc","money"],
                "trim" : "true",
                "charset" : "UTF-8",
                "quoteChar" : "\"",
                "commentPrefix" : "#"
              }
            }
          ]
        }
      }
    }
  ]
}
