### ISSUE TITLE
Is there any document about the new design in sparta2.0

### ISSUE THREAD

**Issue by libratiger** [Stratio/sparta#1898]
This project is awesome, but I just want to know is there any document about the new design in sparta2.0?

I try to send a email to the posted address, but it seems the address is invalid now. Thanks!

**Comment by jpizarrom** [comment]
I also send an email, but the response was

the group you tried to contact (sparta) may not exist, or you may not have permission to post messages to the group.

**Comment by javadba** [comment]
Related:  Is there any LIFE in this project.  My guess: they have decided to close-source this.
