### ISSUE TITLE
I can not open the doc link

### ISSUE THREAD

**Issue by tanghanerla** [Stratio/sparta#1900]
hi,  
  I am new to sparta. I can not open the below link. 
https://stratio.atlassian.net/wiki/spaces/SPARTA1x1x2/pages/106181707/Introduction.
Can someone help me? Thanks you

**Comment by YaffsYale** [comment]
看了你的信息，发现你是自己人，我就用中文了．兄弟，这个需要vpn．如果你没有vpn，可以留个邮箱给我，我可以把文档发给你．我存了一份pdf．看看文档的确帮助很大．

**Comment by tanghanerla** [comment]
我的邮箱是 147423064@qq.com 。多谢了啊。

**Comment by lingbo229** [comment]
@YaffsYale @tanghanerla 我也打不开这个网址了，用了vpn也不行，麻烦也把文档发一份给我吧，1093790620@qq.com 。谢谢了

**Comment by liuyinping** [comment]
@YaffsYale 麻烦你也给我发一份文档吧，我试了配置reference.conf文件不下10次，实在搞不定了。liuyinping2001@163.com  ， 谢谢了！！！

**Comment by bit-jmm** [comment]
@YaffsYale 兄弟，麻烦也发一份文档给我哈，非常感谢。邮箱：bit-jmm@163.com

**Comment by foxgarden** [comment]
@YaffsYale @tanghanerla 现在链接已经失效了，翻墙也没用，发我一份pdf吧谢谢！ 553279787@qq.com

**Comment by KnifeFly** [comment]
> 看了你的信息，发现你是自己人，我就用中文了．兄弟，这个需要vpn．如果你没有vpn，可以留个邮箱给我，我可以把文档发给你．我存了一份pdf．看看文档的确帮助很大．
@YaffsYale  大哥，麻烦也给我发一份吧，我的邮箱是yjdy123@gmail.com，谢谢
