### ISSUE TITLE
Word-count example

### ISSUE THREAD

**Issue by danielcsant** [Stratio/Sparta#202]
Example for an easy understanding of SpaRkTA

**Comment by gserranojc** [comment]
HierarchyBucket is useful for this example?

**Comment by danielcsant** [comment]
HierarchyBucket buckets by tails or by heads: For example for the string "www.stratio.com" will bucket by tails
- www.stratio.com
- stratio.com
- com

I believe we could make a similar Bucketer for the word-count

**Comment by gserranojc** [comment]
Finally I make one operator for this issue.
