### ISSUE TITLE
GeoHashBucketer is not working in C*

### ISSUE THREAD

**Issue by danielcsant** [Stratio/Sparta#235]
[WARN - org.apache.spark.Logging$class.logWarning(Logging.scala:71)] Lost task 1.0 in stage 46.0 (TID 71, localhost): com.datastax.spark.connector.types.TypeConversionException: Cannot convert object List(42.76240987703204, -3.0458100233227015) of type class scala.collection.immutable.$colon$colon to java.nio.ByteBuffer.
    at com.datastax.spark.connector.types.TypeConverter$$anonfun$convert$1.apply(TypeConverter.scala:42)

**Comment by gserranojc** [comment]
When I finish my issue that assign one type to each dimension, we can control the format to save this Array(Double) in Cassandra

**Comment by gserranojc** [comment]
This issue was corrected in the PR dimensionValues Types
