### ISSUE TITLE
Policy DTO's refactor (cubes)

### ISSUE THREAD

**Issue by danielcsant** [Stratio/Sparta#255]
Rename rollups to cubes and change structure as  is in the policy draft

**Comment by gserranojc** [comment]
The new draft is:

{
  "name": "policy-draft",
  "duration": 10000,
  "saveRawData": "false",
  "rawDataParquetPath": "myTestParquetPath",
  "checkpointDir": "checkpoint",
  "timeBucket": "minute",
  "checkpointGranularity": "minute",
  "checkpointInterval": 30000,
  "checkpointTimeAvailability": 60000,
  "inputs": [
    {
      "name": "in-kafka",
      "elementType": "KafkaInput",
      "configuration": {
        "topics": "zion2:1",
        "kafkaParams.zookeeper.connect": "localhost:2181",
        "kafkaParams.group.id": "kafka-pruebas",
        "storageLevel": "MEMORY_AND_DISK_SER_2"
      }
    }
  ],
  "dimensions": [
    {
      "name": "appName"
    },
    {
      "name": "timestamp",
      "dimensionType": "DateTimeDimension"
    },
    {
      "name": "geo",
      "dimensionType": "GeoHashDimension"
    }
  ],
  "cubes": [
    {
      "cube": "time",
      "precisions": [
        {
          "dimension": "timestamp",
          "precision": "minute"
        }
      ],
      "multiplexer": "false",
      "operators": ["count-operator", "max-operator"],
      "outputs": ["out-mongo"]
    },
    {
      "cube": "appName",
      "precisions": [
        {
          "dimension": "appName"
        },
        {
          "dimension": "timestamp",
          "precision": "minute"
        }
      ],
      "multiplexer": "false",
      "operators": ["count-operator"],
      "outputs": ["out-mongo"]
    },
    {
      "cube": "session",
      "precisions": [
        {
          "dimension": "session"
        },
        {
          "dimension": "timestamp",
          "precision": "minute"
        }
      ],
      "operators": ["count-operator"],
      "outputs": ["out-mongo"]
    }
  ],
  "operators": [
    {
      "name": "count-operator",
      "elementType": "CountOperator",
      "configuration": {}
    },
    {
      "name": "max-operator",
      "elementType": "MaxOperator",
      "configuration": {
        "inputField": "responseTime"
      }
    }
  ],
  "outputs": [
    {
      "name": "out-mongo",
      "elementType": "MongoDbOutput",
      "configuration": {
        "host": "localhost",
        "port": 27017,
        "dbName": "sparkta"
      }
    },
    {
      "name": "out-elasticsearch",
      "elementType": "ElasticSearchOutput",
      "configuration": {
        "nodes": "localhost",
        "defaultPort": "9200",
        "dateType": "timestamp",
        "indexMapping": "day"
      }
    }
  ],
  "parsers": [
    {
      "name": "morphline-parser",
      "elementType": "MorphlinesParser",
      "configuration": {
        "morphline": {
          "id": "morphline1",
          "importCommands": [
            "org.kitesdk.**"
          ],
          "commands": [
            {
              "readJson": {}
            },
            {
              "extractJsonPaths": {
                "paths": {
                  "appName": "/appName",
                  "method": "/method",
                  "datetime": "/date",
                  "appCountry": "/appCountry",
                  "appPlatform": "/appPlatform",
                  "appVersion": "/appVersion",
                  "uid": "/uid",
                  "device": "/device",
                  "latitude": "/latitude",
                  "longitude": "/longitude",
                  "osVersion": "/osVersion",
                  "lang": "/lang",
                  "appLang": "/appLang",
                  "user_id": "/user_id",
                  "connection": "/connection",
                  "timestamp": "/timestamp",
                  "session": "/session",
                  "extra1": "/extra1",
                  "extra2": "/extra2",
                  "extra3": "/extra3",
                  "source": "/source",
                  "environment": "/environment",
                  "platform": "/platform",
                  "responseTime": "/responseTime"
                }
              }
            },
            {
              "addValues": {
                "geo": "@{latitude}__@{longitude}"
              }
            },
            {
              "removeFields": {
                "blacklist": [
                  "literal:_attachment_body",
                  "literal:message"
                ]
              }
            }
          ]
        }
      }
    },
    {
      "name": "timestamp",
      "elementType": "DateTimeParser",
      "configuration": {
        "timestamp": "autoGenerated"
      }
    }
  ]
}
