### ISSUE TITLE
Apache Solr output plugin

### ISSUE THREAD

**Issue by raulsaeztapia** [Stratio/Sparta#306]
Would be possible to develop a plugin for send output to Apache Solr?

These guys has published a plugin on Spark:

[LucidWorks/spark-solr](https://github.com/LucidWorks/spark-solr)
[Spark - Solr Integration](http://es.slideshare.net/thelabdude/apachecon-na-2015-spark-solr-integration)

**Comment by raulsaeztapia** [comment]
As long as possible, we need this for **CDH 5.4.0** that contains **Apache Solr 4.10.3**

**Comment by raulsaeztapia** [comment]
### Awesome!!!

We have aggregations on Apache Solr 4.10.3 after develop this and other Issues:
* I cant use Solr output with an existing index #741 
* Index created in Solr automatically, only for local filesystem #743 

The claim was to read from Kafka messages of JSON type, to use morphline transformation, to make aggregations using some operations implemented in Sparkta, and store these aggregations and some other fields in Solr, but in a custom existing index.

Great Job guys!! @danielcsant @sgomezg @anistal @gserranojc @arinconstrio @Gschiavon and others!!

**Comment by raulsaeztapia** [comment]
Hi guys,

I want share with you some charts of Sparkta after running at near **23 hours** with a **three cubes** policy:

![captura de pantalla de 2015-10-09 10 27 26](https://cloud.githubusercontent.com/assets/6919414/10389370/299ea65c-6e71-11e5-9975-210508c44831.png)

Here you can see our **Batch Processing Statistics**, and you should know that our window interval is **5 seconds**:
![captura de pantalla de 2015-10-09 10 31 58](https://cloud.githubusercontent.com/assets/6919414/10389391/4c94125a-6e71-11e5-8561-1a44bc748de6.png)

I hope these are useful.

**Comment by sgomezg** [comment]
Hi Raúl,

Thanks a lot!
