### ISSUE TITLE
Multiple StreamingContext

### ISSUE THREAD

**Issue by EtaCassiopeia** [Stratio/Sparta#436]
I`m wondering that how Sparkta creates multiple application per aggregation policy.when a "CreateContext" message is sent to the StreamingActor, it uses SparkContextFactory object (from StreamingContextService) that returns same SparkContext and StremingContext on each JVM, and as mentioned in the Spark docs "A SparkContext can be re-used to create multiple StreamingContexts, as long as the previous StreamingContext is stopped (without stopping the SparkContext) before the next StreamingContext is created.".I`m confused! does Sparkta create multiple StremingContext for each Aggregation policy or create separated applications on different JVMs to accomplish this? I`m planning to create streaming supervisor actor on separate JVM or machine with it`s own contexes, is this approach will solve the problem? Can you tell me what I missed?

**Comment by sgomezg** [comment]
Hi Mohsen,

Sparkta will support multiple StreamingContext via [spark-jobserver](https://github.com/spark-jobserver/spark-jobserver) integration.  It is in the roadmap, and currently we are working hard on this spike. Sparkta will manage one job (context) per policy and will send it to a cluster with a resource manager like Mesos or Yarn. In this manner, you will be able to run multiple policies in the same cluster. Please, let me know if I can help you with other issues.

More info about this: https://issues.apache.org/jira/browse/SPARK-2243

Best,
Sergio

**Comment by zainalpour** [comment]
Hi Sergio,

Thank you very much for the prompt reply. In the SparkJobServer project there is nothing special except using a custom class loader named ContextURLClassLoader to create a context in the JobManagerActor class. does all the magic done here?

**Comment by sgomezg** [comment]
Hi Mohsen. 

There is no magic actually. The resource manager split the cluster for you. Think about little pieces of cluster isolated for each job. One job, one piece.

Best,
Sergio

**Comment by gserranojc** [comment]
Hi Mohsen,

In Sparkta now is possible to generate multiple policies with cluster execution, and you can have more than one Spark context with the resource manager.

Regards Jose Carlos.
