### ISSUE TITLE
Sandbox - Spartka not running successfully

### ISSUE THREAD

**Issue by arlejeun** [Stratio/Sparta#450]
Well, I'm new in the Sparkta community and I'm excited to play with the sandbox but I'm running into an issue starting sparkta.

After starting zookeeper, I tried to run sparkta with the following command
$sh {SPARKTA_HOME}/bin/run but it returns the following error with the main class com.stratio.sparkta.driver.Sparkta not found.

Can you please help me to start sparkta on the sandbox?

**Comment by Brezyll** [comment]
Hi arlejeun,

As you said the first thing is run zookeeper.
After that, try 

`cd /opt/sds/sparkta`

`sh bin/run`

It should work properly, if you have any problem don't hesitate in contact us again.
Also you can find more information [here](http://docs.stratio.com/modules/sparkta/development/sandbox.html).
Regards.
