### ISSUE TITLE
Error in Sparkta's Sandbox

### ISSUE THREAD

**Issue by gbecares** [Stratio/Sparta#499]
After typing the command "bin/run" inside the "/opt/sds/sparkta" directory I get this error:

**[vagrant@sparkta sparkta]$ sh bin/run
Error: no se ha encontrado o cargado la clase principal com.stratio.sparkta.driver.Sparkta**

**Comment by Blinx7** [comment]
Solved :)

**Comment by dmorales-stratio** [comment]
Please, give information about the resolution. It is not useful to close an
issue without information about how it has been solved.

Thanks

2015-08-05 10:53 GMT+02:00 Gonzalo Bécares <notifications@github.com>:

> Solved :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Stratio/sparkta/issues/499#issuecomment-127920312>.
>



-- 

David Morales de Frías  ::  +34 607 010 411 :: @dmoralesdf
<https://twitter.com/dmoralesdf>


<http://www.stratio.com/>
Vía de las dos Castillas, 33, Ática 4, 3ª Planta
28224 Pozuelo de Alarcón, Madrid
Tel: +34 91 828 6473 // www.stratio.com // *@stratiobd
<https://twitter.com/StratioBD>*

**Comment by danielcsant** [comment]
There were some dependencies missed in the sandbox. That was the reason *com.stratio.sparkta.driver.Sparkta* was not found.

There are already a working sandbox updated with the hotfix

**Comment by dmorales-stratio** [comment]
Perfect¡ Remember to always explain what has been done to fix the issue or
the resolution itself.

Thanks

2015-08-05 11:15 GMT+02:00 Daniel Carroza Santana <notifications@github.com>
:

> There were some dependencies missed in the sandbox. That was the reason
> *com.stratio.sparkta.driver.Sparkta* was not found.
>
> There are already a working sandbox updated with the hotfix
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Stratio/sparkta/issues/499#issuecomment-127927167>.
>



-- 

David Morales de Frías  ::  +34 607 010 411 :: @dmoralesdf
<https://twitter.com/dmoralesdf>


<http://www.stratio.com/>
Vía de las dos Castillas, 33, Ática 4, 3ª Planta
28224 Pozuelo de Alarcón, Madrid
Tel: +34 91 828 6473 // www.stratio.com // *@stratiobd
<https://twitter.com/StratioBD>*
