### ISSUE TITLE
Stratio Sparkta Sandbox's documentation should be checked

### ISSUE THREAD

**Issue by gbecares** [Stratio/Sparta#502]
1. Before typing "sh bin/run", zookeeper must be running (start zookepeer service).
2. The command "sh bin/run" does not open any "Shell"
3. Command "sh bin/run" should be changed to "sudo sh bin/run &> /tmp/sparkta.out &"
4. Why do we need to check if elasticsearch is running in step 4?

**Comment by Gschiavon** [comment]
We will check it. Thanks a lot!
