### ISSUE TITLE
Cassandra Timestamp

### ISSUE THREAD

**Issue by Gschiavon** [Stratio/Sparta#541]
Check if the timestamp in cassandra is the timestamp from the event and not from the system.

**Comment by danielcsant** [comment]
To reproduce this error:
Run a policy with Kafka input aggregating by the event time
Stop policy
Wait some time to populate the kafka topic
Start policy (It should aggregate by the event time but it does not)

**Comment by dvallejo** [comment]
It seems that the same error appears with Mongo as ouput. Could be an error in the Kafka consumer.
