### ISSUE TITLE
Sandbox is not running on Windows10

### ISSUE THREAD

**Issue by dmorales-stratio** [Stratio/Sparta#703]
Due to an issue in virtualbox, sandbox could not install the network interfaces.

https://github.com/mitchellh/vagrant/issues/6059

There is an official workaround. Just downloand and run as administrator

https://www.virtualbox.org/attachment/ticket/14040/VBox-Win10-fix-14040.exe

Let the fix run in the backgound while executing vagrant up.

That should be included in the documentation

**Comment by Gschiavon** [comment]
Ok! we will add this in the documentation.
Thanks.
