### ISSUE TITLE
Druid Output

### ISSUE THREAD

**Issue by compae** [Stratio/Sparta#73]
Output to Druid.

We must use tranquility api (https://github.com/druid-io/tranquility)
One connection in each worker and send the events to the overlord host in druid.

Is necessary implements the conversion to Druid Aggregations:

ImmutableList.of(
    new CountAggregatorFactory("cnt"),
    new LongSumAggregatorFactory("baz", "baz")
);

**Comment by gserranojc** [comment]
Output to Druid, use tranquility api.
