### ISSUE TITLE
when creating new inputs/outputs, when error messages are displayed, if you move among different types, data is saved but error checks are not shown again

### ISSUE THREAD

**Issue by antonioalf** [Stratio/Sparta#869]
Steps to reproduce:
- Try to create a new flume input
- Delete 'localhost' from 'Host' input field
  (Note field is RED)
- Click the 'Kakfa' type icon
- Go back to flume type. Field is still empty, but it is not red anymore.

**Comment by alexrchies** [comment]
Done
