### ISSUE TITLE
Stratio Cassandra index integration

### ISSUE THREAD

**Issue by compae** [Stratio/Sparta#92]
Full text index integration with stratio cassandra implementation.

https://github.com/Stratio/stratio-cassandra

We need create the index in the tables reading the tables schema and send to the connector something like this:

CREATE CUSTOM INDEX tweets_index ON tweets (lucene) 
USING 'com.stratio.cassandra.index.RowIndex'
WITH OPTIONS = {
    'refresh_seconds' : '1',
    'schema' : '{
        fields : {
            body : {type : "text",  analyzer : "english"}
        }
    }'
};

**Comment by gserranojc** [comment]
Full text index integration with stratio cassandra implementation.
